### ISSUE TITLE
Strapi v4 is released

### ISSUE THREAD

**Issue by capsloq** [nazirov91/ra-strapi-rest#34]
Strapi v4 was released a couple of days ago.
Are there any plans to update this procject to make use of the new response format, filters etc. of strapi v4?

https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#delete-an-entry

**Comment by tuxyvarman** [comment]
Hi,

Perhaps it's better to create a new data provider project for the Strapi v4 ? I tried to modify the current data provider but the Strapi v4 doesn't send the same payload. I'm afraid that will make the spaghetti effect if we try to modify the current code for strapi 3 and 4. 
What do you think ?

Best regards.

**Comment by Reggionick** [comment]
Hi,

In [this](https://github.com/code-laundry/ra-strapi-rest) fork I've updated the project in order to be compliant with the new v4 Strapi version. I haven't tested all the functionalities, if you find something broken I could fixit.

@tuxyvarman in my opinion it could be possible to create a breaking changes version, maintaining a version compatible with both v3 and v4 could be painful and unnecessary

@nazirov91 if you agree I could make a PR to your repo.

**Comment by capsloq** [comment]
React Admin is also upgrading to a major version 4.0 in "early 2022"
https://github.com/marmelab/react-admin/issues/5933

Maybe this should be waited for before investing too much time?

Thank you @Reggionick ! Will do some testing on it

**Comment by nazirov91** [comment]
Hi! 

Please see the readme file. I have updated the package to make it work with Strapi V4. Please open a new issue if the problem persists. 

Thanks!
